language: node_js

os:
  - linux
  - osx

services: 
  - xvfb

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

node_js: "10"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update && sudo apt-get install -q libxss-dev; fi

script:
  - npm install -g nyc
  - npx nyc mocha
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn dist; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn dist-all; fi

notifications:
  email:
    on_success: never
    on_failure: change

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file:
    - 'dist/minser.dmg'
    - 'dist/minser.appx'
    - 'dist/minser.exe'
    - 'dist/minser-web-setup.exe'
    - 'dist/minser-i386.AppImage'
    - 'dist/minser-x86_64.AppImage'
    - 'dist/minser-i686.rpm'
    - 'dist/minser-x86_64.rpm'
    - 'dist/minser-amd64.deb'
    - 'dist/minser-i386.deb' 
  skip_cleanup: true
  on:
    tags: true
